// ──────────────────────────────────────────────────────────────────────────
// Offline generator for client/src/components/journal/usStatesGeo.ts
//
// Produces PRE-PROJECTED AlbersUSA SVG path data for the 50 states + DC so the
// Journal visited-states map renders instantly with NO runtime CDN fetch and
// NO runtime d3/topojson dependency (the scope §8.3 lesson: bundle geometry
// locally). us-atlas / topojson-client / d3-geo are DEV/BUILD deps only — they
// are used HERE, at build time, and never imported by app code.
//
// Run from the client/ directory:
//   node scripts/genUsStatesGeo.mjs
//
// Re-run only when you want to regenerate the geometry (e.g. bump us-atlas).
// The committed output (usStatesGeo.ts) is the source of truth the app ships.
//
// The viewBox is locked to 960×600 AlbersUSA so a future journal-PIN layer
// (step 7) can overlay lat/lng via geoAlbersUsa().fitSize([960,600], …) into
// the SAME coordinate space these paths live in.
// ──────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { geoAlbersUsa, geoPath } from 'd3-geo'
import { feature } from 'topojson-client'

const require = createRequire(import.meta.url)
const __dirname = dirname(fileURLToPath(import.meta.url))

const WIDTH = 960
const HEIGHT = 600

// FIPS (numeric, as us-atlas ids them) → 2-letter postal code.
const FIPS_TO_CODE = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO',
  '09': 'CT', '10': 'DE', '11': 'DC', '12': 'FL', '13': 'GA', '15': 'HI',
  '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA', '20': 'KS', '21': 'KY',
  '22': 'LA', '23': 'ME', '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN',
  '28': 'MS', '29': 'MO', '30': 'MT', '31': 'NE', '32': 'NV', '33': 'NH',
  '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH',
  '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI', '45': 'SC', '46': 'SD',
  '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT', '51': 'VA', '53': 'WA',
  '54': 'WV', '55': 'WI', '56': 'WY',
}

// us-atlas (v3) ships states-10m.json with a `states` object keyed by FIPS id
// and a `properties.name` full name. It's high-res; we round path coordinates
// to 1 decimal below (visually identical at 960px, ~half the bytes).
const atlasPath = require.resolve('us-atlas/states-10m.json')

// Round every coordinate in an SVG path `d` to 1 decimal place. At a 960-wide
// viewBox sub-pixel precision is invisible, so this is a free ~40-50% shrink.
const trimPath = d => d.replace(/-?\d+\.\d+/g, m => String(Math.round(+m * 10) / 10))
const topology = JSON.parse(readFileSync(atlasPath, 'utf8'))
const fc = feature(topology, topology.objects.states)

// Fit the AlbersUSA projection to the locked viewBox.
const projection = geoAlbersUsa().fitSize([WIDTH, HEIGHT], fc)
const path = geoPath(projection)

const out = []
for (const f of fc.features) {
  const code = FIPS_TO_CODE[String(f.id).padStart(2, '0')]
  if (!code) continue // skip territories (PR, etc.) — not in our 50 + DC set
  const d = path(f)
  if (!d) continue
  const [cx, cy] = path.centroid(f)
  out.push({
    code,
    name: f.properties.name,
    d: trimPath(d),
    cx: Math.round(cx * 100) / 100,
    cy: Math.round(cy * 100) / 100,
  })
}
out.sort((a, b) => a.code.localeCompare(b.code))

const header = `// AUTO-GENERATED by client/scripts/genUsStatesGeo.mjs — DO NOT EDIT BY HAND.
// Pre-projected AlbersUSA SVG paths for the 50 states + DC. Bundled locally so
// the Journal visited-states map renders with no runtime CDN fetch and no
// runtime d3/topojson dependency. Regenerate with: node scripts/genUsStatesGeo.mjs
// (run from client/). viewBox is locked to ${WIDTH}x${HEIGHT} AlbersUSA so a
// future pin layer can share this coordinate space.
`

const body = `${header}
export interface UsState {
  /** 2-letter postal code (DC included; DC does not count toward the 50). */
  code: string
  /** Full state name, for tooltips / the legend. */
  name: string
  /** Pre-projected SVG path data in the ${WIDTH}x${HEIGHT} viewBox below. */
  d: string
  /** Projected centroid — used to place a tap-target dot for tiny states. */
  cx: number
  cy: number
}

export const US_ALBERS_VIEWBOX = '0 0 ${WIDTH} ${HEIGHT}'

export const US_STATES: UsState[] = ${JSON.stringify(out, null, 2)}
`

const target = resolve(__dirname, '../src/components/journal/usStatesGeo.ts')
writeFileSync(target, body)
console.log(`Wrote ${out.length} states (+DC) to ${target}`)
