import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import { PackingCategory } from '../../types'

/**
 * Printable packing checklist — a PAPER checklist for pen use. Every checkbox
 * renders EMPTY by design: on-screen packed state is deliberately ignored so
 * the printout works for the next pack-up regardless of what's been ticked in
 * the app. Follows TripPDF's conventions (Helvetica, 9pt base, RV Blue
 * accents, dynamic-import-on-click at the call site).
 */

const GREEN  = '#1F6F8B'
const GRAY_9 = '#111827'
const GRAY_7 = '#374151'
const GRAY_5 = '#6B7280'

const s = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 9,
    padding: 36,
    color: GRAY_7,
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: GREEN,
    paddingBottom: 8,
    marginBottom: 14,
  },
  title: { fontSize: 16, fontFamily: 'Helvetica-Bold', color: GRAY_9 },
  subtitle: { fontSize: 10, color: GRAY_5, marginTop: 3 },
  category: { marginBottom: 12 },
  categoryName: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: GREEN,
    marginBottom: 5,
    paddingBottom: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  checkbox: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: GRAY_5,
    borderRadius: 1.5,
    marginRight: 7,
  },
  itemName: { fontSize: 9.5, color: GRAY_7 },
  required: { color: '#DC2626' },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 36,
    right: 36,
    fontSize: 7.5,
    color: GRAY_5,
    textAlign: 'center',
  },
})

export interface PackingListPDFProps {
  tripName: string
  /** Pre-formatted date line for the header, e.g. "Jun 20 – Jul 2, 2026".
   *  Empty string hides the line. */
  dateRange: string
  categories: PackingCategory[]
}

export function PackingListPDF({ tripName, dateRange, categories }: PackingListPDFProps) {
  const totalItems = categories.reduce((sum, c) => sum + c.items.length, 0)
  return (
    <Document>
      <Page size="LETTER" style={s.page}>
        <View style={s.header}>
          <Text style={s.title}>Packing List — {tripName}</Text>
          <Text style={s.subtitle}>
            {dateRange ? `${dateRange} · ` : ''}{totalItems} items · * = essential
          </Text>
        </View>

        {categories.map((cat, ci) => (
          <View key={ci} style={s.category} wrap={false}>
            <Text style={s.categoryName}>{cat.category}</Text>
            {cat.items.map((item, ii) => (
              <View key={ii} style={s.itemRow}>
                {/* Always empty — pen goes here. */}
                <View style={s.checkbox} />
                <Text style={s.itemName}>
                  {item.name}
                  {item.required ? <Text style={s.required}> *</Text> : null}
                </Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={s.footer} fixed>
          Generated by RoamReady · roamready.ai
        </Text>
      </Page>
    </Document>
  )
}
